package com.arko.model.POJO;

import java.sql.Timestamp;

public class Passenger {
    // Database Fields - Ordered based on image_ab2e7b.png
    private int passengerID;           // PK - Auto-increment
    private String firstName;
    private String lastName;
    private String middleInitial;      // VARCHAR(2)
    private String contactNumber;
    private int age;
    private char sex;                  // 'M' or 'F'
    private String passengerDirection; // "Upstream" or "Downstream"
    private String passengerStatus;    // Default: "Waiting", "Boarded", "Completed"
    private String classification;     // "Student", "Senior", "PWD", "Regular"
    private Timestamp registrationTimeStamp; //Set in DAO
    private Timestamp completionTimeStamp;   // Set upon alighting
    private String boardingCode;       // e.g., GUA-2026-03-20-004
    private int originStationID;       // FK - Set via SessionManager
    private int destinationStationID;  // FK - Staff Input
    private int tripID;                // FK - Set when passenger boards a vessel
    private int staffStampID;          // FK - Set via SessionManager

    private String fullName;   // Dedicated field for the Manifest UI
    private String originCode; // LOCAL: For 3-letter Origin (e.g., GUA)
    private String destinationCode; // LOCAL: Ensure this exists for the table join

    // Constructor for NEW passengers (InputForm Panel)
    public Passenger(String firstName, String lastName, String middleInitial,
                     String contactNumber, int age, char sex,
                     String classification, int destinationStationID) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.middleInitial = middleInitial;
        this.contactNumber = contactNumber;
        this.age = age;
        this.sex = sex;
        this.classification = classification;
        this.destinationStationID = destinationStationID;

        /* EXCLUDED FIELDS (To be handled by the DAO or Database):
           - passengerID: Auto-incremented by MySQL.
           - passengerDirection: Set in DAO based on Destination Station sequence.
           - passengerStatus: Defaulted to 'Waiting' in DB/DAO.
           - registrationTimeStamp: Generated by CURRENT_TIMESTAMP in DB.
           - completionTimeStamp: Updated via Manifest Controller upon alighting.
           - boardingCode: Generated in DAO (StationCode + Date + Sequence).
           - originStationID: Pulled from SessionManager in DAO.
           - tripID: Updated in DAO during the Boarding Engine execution.
           - staffStampID: Pulled from SessionManager in DAO.
        */
    }

    // 2. Empty Constructor for Retrieving from DAO
    public Passenger() {}

    // --- Getters and Setters ---
    public int getPassengerID() { return passengerID; }
    public void setPassengerID(int id) { this.passengerID = id; }

    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }

    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }

    public String getMiddleInitial() { return middleInitial; }
    public void setMiddleInitial(String mi) { this.middleInitial = mi; }

    public String getContactNumber() { return contactNumber; }
    public void setContactNumber(String contact) { this.contactNumber = contact; }

    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }

    public char getSex() { return sex; }
    public void setSex(char sex) { this.sex = sex; }

    public String getPassengerDirection() { return passengerDirection; }
    public void setPassengerDirection(String direction) { this.passengerDirection = direction; }

    public String getPassengerStatus() { return passengerStatus; }
    public void setPassengerStatus(String status) { this.passengerStatus = status; }

    public String getClassification() { return classification; }
    public void setClassification(String classification) { this.classification = classification; }

    public Timestamp getRegistrationTimeStamp() { return registrationTimeStamp; }
    public void setRegistrationTimeStamp(Timestamp ts) { this.registrationTimeStamp = ts; }

    public Timestamp getCompletionTimeStamp() { return completionTimeStamp; }
    public void setCompletionTimeStamp(Timestamp ts) { this.completionTimeStamp = ts; }

    public String getBoardingCode() { return boardingCode; }
    public void setBoardingCode(String code) { this.boardingCode = code; }

    public int getOriginStationID() { return originStationID; }
    public void setOriginStationID(int id) { this.originStationID = id; }

    public int getDestinationStationID() { return destinationStationID; }
    public void setDestinationStationID(int id) { this.destinationStationID = id; }

    public int getTripID() { return tripID; }
    public void setTripID(int id) { this.tripID = id; }

    public int getStaffStampID() { return staffStampID; }
    public void setStaffStampID(int id) { this.staffStampID = id; }

    public String getDestinationCode() {
        return destinationCode;
    }
    public void setDestinationCode(String destinationCode) {
        this.destinationCode = destinationCode;
    }

    public String getFullName() {return fullName;}
    public void setFullName(String fullName) {this.fullName = fullName;} //CONCATENATES FIRST AND LAST NAME

    public String getOriginCode() {return originCode;}
    public void setOriginCode(String originCode) {this.originCode = originCode;}
}